CREATE DATABASE SMARTPORTABLES;

USE SMARTPORTABLES;
CREATE TABLE USERS(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(200),
   PASSWORD VARCHAR(200),
   CREDNO VARCHAR(200),
   UTYPE VARCHAR(200),
   ADDRESS TEXT,
   PRIMARY KEY (ID)
);	

USE SMARTPORTABLES;
CREATE TABLE ORDERS(
   ID VARCHAR(200) NOT NULL,
   NAME VARCHAR(200),
   DESCRIPTION TEXT,
   PRICE DOUBLE,
   ORDERDATE DATE,
   STATUS VARCHAR(200),
   BUYER VARCHAR(200),
   BUYER_ID INT,
   RETAILER_ID INT,
   FOREIGN KEY (BUYER_ID) REFERENCES USERS(ID),
   FOREIGN KEY (RETAILER_ID) REFERENCES USERS(ID),
   PRIMARY KEY (ID)
);	
