use bestbid;
select * from PRODUCTS;

CREATE TABLE PRODUCTS(
   ID INT NOT NULL AUTO_INCREMENT,
   
   HIGHEST_BID VARCHAR(200),
   HIGHEST_BID_BUYER VARCHAR(200),
   CATEGORY VARCHAR(200),
   WARRANTY VARCHAR(200),
   SELLER_NAME VARCHAR(200),
   SELLER_ZIP VARCHAR(200),
   SELLER_CITY VARCHAR(200),
   MANUFACTURE_NAME VARCHAR(200),
   HIGHEST_BID_BUYER_EMAILID VARCHAR(200),
   HIGHEST_BID_BUYER_PHONE VARCHAR(200),
   PRIMARY KEY (ID)
);	

INSERT INTO `bestbid`.`products`
(`PRODUCT_NAME`,
`HIGHEST_BID`,
`HIGHEST_BID_BUYER`,
`CATEGORY`,
`WARRANTY`,
`SELLER_NAME`,
`SELLER_ZIP`,
`SELLER_CITY`,
`MANUFACTURE_NAME`,
`HIGHEST_BID_BUYER_EMAILID`,
`HIGHEST_BID_BUYER_PHONE`)
VALUES
("LG-203",
"293",
"RAJ",
"TV",
"23",
"SUJAY",
"60616",
"CHICAGO",
"LG",
"RAJKOTAK@GMAIL.COM",
"3128749294");

TRUNCATE table `BESTBID`.`PRODUCTS`;